services:
    worker:
        build: .
        command: python main.py
        environment:
            PYTHONUNBUFFERED: "1"
        volumes:
            - private_data:/app/private

volumes:
    private_data:
